services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: energysense-jenkins
    network_mode: host
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/oussema/.m2:/var/jenkins_home/.m2
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true -Dhudson.plugins.git.GitSCM.ALLOW_LOCAL_CHECKOUT=true
      - JENKINS_OPTS=--httpPort=8090
      - DOCKER_HUB_USER=oussemamsehli
  sonarqube:
    image: sonarqube:community
    container_name: energysense-sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
